@startuml

title __SERVICE's Class Diagram__\n

  namespace by.training.nc.sd3 {
    namespace service {
      interface by.training.nc.sd3.service.BillingAccountDataService {
          {abstract} + addMoney()
          {abstract} + ban()
          {abstract} + deleteBillingAccountById()
          {abstract} + getAll()
          {abstract} + getBillingAccountById()
          {abstract} + getBillingAccountsByOwnerId()
          {abstract} + saveBillingAccount()
          {abstract} + unBan()
      }
    }
  }
  

  namespace by.training.nc.sd3 {
    namespace service {
      interface by.training.nc.sd3.service.ProductInstanceDataService {
          {abstract} + changeStatus()
          {abstract} + delete()
          {abstract} + getSubscriptionUnitsByUserId()
          {abstract} + save()
          {abstract} + saveAll()
      }
    }
  }
  

  namespace by.training.nc.sd3 {
    namespace service {
      interface by.training.nc.sd3.service.ProductOfferingDataService {
          {abstract} + ban()
          {abstract} + getAll()
          {abstract} + getProductOfferingByCategory()
          {abstract} + getProductOfferingById()
          {abstract} + getProductOfferingByName()
          {abstract} + save()
          {abstract} + unBan()
      }
    }
  }
  

  namespace by.training.nc.sd3 {
    namespace service {
      interface by.training.nc.sd3.service.StatisticsEntryDataService {
          {abstract} + getStatisticsByCategory()
          {abstract} + getStatisticsForBillingAccount()
      }
    }
  }
  

  namespace by.training.nc.sd3 {
    namespace service {
      interface by.training.nc.sd3.service.UserAccountDataService {
          {abstract} + ban()
          {abstract} + changeActiveBillingAccount()
          {abstract} + getAll()
          {abstract} + getUserAccountByData()
          {abstract} + getUserAccountById()
          {abstract} + saveUserAccount()
          {abstract} + subscriptionsQuantity()
          {abstract} + unBan()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
