@startuml

title __SERVICE's Class Diagram__\n

  namespace by.training.nc.sd3 {
    namespace service {
      interface by.training.nc.sd3.service.BillingAccountService {
          {abstract} + addMoney()
          {abstract} + ban()
          {abstract} + delete()
          {abstract} + getAll()
          {abstract} + getAllByOwnerId()
          {abstract} + getById()
          {abstract} + save()
          {abstract} + unBan()
      }
    }
  }
  

  namespace by.training.nc.sd3 {
    namespace service {
      interface by.training.nc.sd3.service.ProductInstanceService {
          {abstract} + changeStatus()
          {abstract} + delete()
          {abstract} + getByBillingAccountId()
          {abstract} + getById()
          {abstract} + getByUserId()
          {abstract} + getProductInstances()
          {abstract} + save()
          {abstract} + save()
          {abstract} + update()
      }
    }
  }
  

  namespace by.training.nc.sd3 {
    namespace service {
      interface by.training.nc.sd3.service.ProductOfferingService {
          {abstract} + ban()
          {abstract} + getProductOfferingByName()
          {abstract} + getProductOfferings()
          {abstract} + getProductOfferingsByCategory()
          {abstract} + getSubscriptionById()
          {abstract} + save()
          {abstract} + unBan()
      }
    }
  }
  

  namespace by.training.nc.sd3 {
    namespace service {
      interface by.training.nc.sd3.service.StatisticsService {
          {abstract} + getStatisticsForBillingAccount()
          {abstract} + getStatisticsForCategory()
      }
    }
  }
  

  namespace by.training.nc.sd3 {
    namespace service {
      interface by.training.nc.sd3.service.UserAccountService {
          {abstract} + ban()
          {abstract} + changeActiveBillingAccount()
          {abstract} + getAll()
          {abstract} + getSubscriptionsQuantity()
          {abstract} + getUserAccount()
          {abstract} + getUserAccountById()
          {abstract} + getUserAccountByName()
          {abstract} + save()
          {abstract} + unBan()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
